RUN_LOG="./logs.txt"
RUN_WATCH="run-settings.sh include src CMakeLists.txt inicpp"
RUN_BUILD_COMMAND="(cmake -DDEBUG=OFF -DOPTIMIZE=ON . && cmake --build . -- -j8)"
RUN_EXECUTABLE="./thex"
RUN_ARGUMENTS="test.bin"
