RUN_LOG="./logs.txt"
RUN_WATCH="run-settings.sh include src CMakeLists.txt inicpp configs.ini"
RUN_BUILD_COMMAND="(cmake -DDEBUG=ON . && cmake --build .)"
RUN_EXECUTABLE="./thex"
RUN_ARGUMENTS="test.bin"
