# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Build

on: 
  workflow_dispatch: 
  pull_request: 
    branches: [ "main" ]
  push: 
    branches: [ "main" ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: true
      matrix:
        debug: [ "ON", "OFF" ]

    steps:
    - uses: actions/checkout@v4

    - name: Download dependencies
      run: |
        sudo apt update 
        sudo apt install -y libncurses-dev clang cmake
        clang --version
        
    - name: Running CMake
      run: |
        export CXX=clang++
        export CC=clang
        cmake . -DDEBUG="${{ matrix.debug }}"

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build .

    - name: "Set label"
      run: |
        if [ "${{ matrix.debug }}" == "ON" ]; then
          echo "label=debug" >> $GITHUB_ENV
        else
          echo "label=release" >> $GITHUB_ENV
        fi

    - name: Creating Artifactic
      uses: actions/upload-artifact@v3
      with:
        name: thex_linux_x86-64_${{ env.label }}
        path: ./thex
