# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake on multiple platforms

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download dependencies
      run: |
        sudo apt update 
        sudo apt install -y libncurses-dev clang cmake

    - name: Running CMake
      run: cmake .

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build .

    - name: Creating Artifactic
      uses: actions/upload-artifact@v3
      with:
        name: linux-x86
        path: ./thex
