name: Build for Linux

on: 
  workflow_dispatch: 
  pull_request: 
    branches: [ "main" ]
  push: 
    branches: [ "main" ]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        debug: [ "ON", "OFF" ]
        optimize: [ "ON", "OFF" ]

        exclude:
          - debug: "ON"
            optimize: "ON"

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Download dependencies
      run: |
        sudo apt update 
        sudo apt install -y libncurses-dev clang cmake
        clang --version
        
    - name: Running CMake
      run: |
        export CXX=clang++
        export CC=clang
        cmake . -DDEBUG="${{ matrix.debug }}" -DOPTIMIZE="${{ matrix.optimize }}"

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build .

    - name: "Set label"
      run: |
        label=unknown

        if [ "${{ matrix.debug }}" == "ON" ]; then
          label=debug
        else
          label=release
        fi

        if [ "${{ matrix.optimize }}" == "ON" ]; then
          label="$label-optimized"
        fi
        
        echo "label=$label" >> $GITHUB_ENV
    - name: Creating Artifactic
      uses: actions/upload-artifact@v4
      with:
        name: thex_linux_x86-64_${{ env.label }}
        path: ./thex
