name: Build for windows

on: 
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
  push: 
    branches: [ "main" ]

jobs:
  windows-build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make
            mingw-w64-x86_64-ncurses
      
      - name: Setup WINGW env
        run: |
          echo "C:\msys64\mingw64\bin" >> $GITHUB_PATH
          echo "C:\msys64\usr\bin" >> $GITHUB_PATH

      - name: Running CMake
        run: |
          cmake -G "WinGW Makefiles" .

      - name: Build
        run: wingw32-make
  
      - name: Creating Artifactic
        uses: actions/upload-artifact@v3
        with:
          name: thex_windows_x86-64
          path: ./thex.exe
